### ISSUE TITLE
Direct navigation to pages other than the root URL breaks without service workers

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/personal-logger#11]
This means that creating or deleting resources results in 404 page on mobile.

| Device | Server | Works? |
|:---|:---|:---:|
| Laptop | localhost | ✓ |
| Laptop | *.now.sh | ✓ |
| Mobile | localhost | ✓ |
| Mobile | *.now.sh | ✖ |

**Comment by bvaughn** [comment]
Can't repro in iOS simulator on Safari.

**Comment by ishankbahl** [comment]
Hey @bvaughn , wasn't able to recreate the bug on my device. Direct navigation didn't break anything.

**Comment by bvaughn** [comment]
Really! So you can successfully eg delete things?

This consistently 404s for me, on device and simulator

**Comment by ishankbahl** [comment]
Was able to delete things successfully.

**Comment by bvaughn** [comment]
Strange. Any time I try to create a new item, or delete one, or navigate to any page other than the root URL- I get a 404 back. This happens on my iPhone for Chrome and Safari, and on my simulator for Safari.

**Comment by robertcoopercode** [comment]
I've managed to reproduce the bug on my iPhone 8 using Chrome. If I refresh a page or try deleting an item, I get a 404.

**Comment by bvaughn** [comment]
👍

I see that behavior in all of my iOS browsers, on all iOS devices/simulators.

**Comment by bvaughn** [comment]
Ah. I believe this is actually a service-worker issue. (Mobile Safari doesn't support them.)

Looking a little more closely at this, `curl https://personal-logger.now.sh/foods` returns a 404 response, which is consistent with what I'm seeing on mobile.

That same URL in (desktop) Chrome is handled by the service worker, which is what redirects it to the SPA.

**Comment by bvaughn** [comment]
Confirmed by visiting [https://personal-logger.now.sh/foods](https://personal-logger.now.sh/foods) on Chrome in Android. Got the 404 response. Then visited [https://personal-logger.now.sh](https://personal-logger.now.sh) before _retrying_  [https://personal-logger.now.sh/foods](https://personal-logger.now.sh/foods) and it worked the second time (because the service worker had been installed).

**Comment by bvaughn** [comment]
So I think the solution to this is to configure Now to do a 404 redirect for me.

**Comment by bvaughn** [comment]
I tried following the [Now create-react-app guide](https://zeit.co/docs/examples/create-react-app) and using `serve` for routing, but this caused my deploys to start failing with an [out of memory error](https://zeit.co/bvaughn/personal-logger/flxufjmtlv/logs). This might be due to the fact that I'm on the cheapest plan.

For now, I think I'll just fix this by replacing the [`BrowserRouter`](https://reacttraining.com/react-router/web/api/BrowserRouter) with the [`HashRouter`](https://reacttraining.com/react-router/web/api/HashRouter).

**Comment by bvaughn** [comment]
Resolved via d5ad60c
