### ISSUE TITLE
Report view

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/personal-logger#24]
Create a view that shows all entries, ordered by date, with short, text-only summaries.

This can be useful for sharing with a physician, or for visually scanning for trends (until automated tools exist).

**Comment by bvaughn** [comment]
Maybe this can be the default landing page. Maybe clicking the centered title can route to this page.

**Comment by MikeTheCanuck** [comment]
I didn't know why the "homepage" felt off to me (I didn't even dislike it), but this would be a significant improvement - a decent data summary as the default experience for a data-capture tool strikes me as a big UX win.

**Comment by bvaughn** [comment]
Well there isn't really a home-page now. Issue #4 is about creating one. But at least this would be a reasonable starting point, and I need to create this view anyway, for an upcoming doctor appointment. 😄

**Comment by bvaughn** [comment]
I've deployed an initial stab at this, although I plan to iterate on it to add more options (like "export")

**Comment by bvaughn** [comment]
Export/download option has been added. Going to consider this good enough for now. Can follow up and improve in #4.
