### ISSUE TITLE
Add "meal size" attribute to food entries

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/personal-logger#26]
Add a conditional enum to the `EditFoodForm` for `type === "food"` records to specify a meal `size`: "snack", "small", "large"

**Comment by prattheev** [comment]
@bvaughn I'll help you with this :smiley:

**Comment by bvaughn** [comment]
Great. 🙂 Send a PR my way

**Comment by bvaughn** [comment]
Hey @prattheev 😄 Just wondering if you were still working on this. Not trying to rush! But if you've decided you don't have time, just let me know and I'll be happy to implement it.

**Comment by bvaughn** [comment]
Okay. I'm putting it back into the pool. 😄

**Comment by robertcoopercode** [comment]
Hey @bvaughn I can take a stab at this. I can put some work into it tomorrow and see if I get anywhere. I'm unfamiliar with some stuff (like Flow), but I think I should be able to add this feature.

**Comment by bvaughn** [comment]
Sounds good! Go for it! :)
